config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  namespace :api do
    get "/users_by_email" => "users_by_emails#show", :as => :users_by_email

    resources :favorites, only: [:create, :destroy]
  end

  resources :properties, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  # validates :city, presence: true
  # validates :state, presence: true
  # validates :country, presence: true
  # validates :address_1, presence: true

  geocoded_by :address
  after_validation :geocode, if: -> { address.present? && latitude.blank? && longitude.blank? }

  def address
    [address_1, address_2, city, state, zip_code, country].compact.join(", ")
  end
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  validates :name, presence: true
  validates :headline, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :address_1, presence: true

  monetize :price_cents, allow_nil: true
  has_many_attached :images, dependent: :destroy
  has_many :reviews, as: :reviewable
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user

  geocoded_by :address
  after_validation :geocode, if: -> { latitude.blank? && longitude.blank? }
  # after_validation :geocode, unless: ->(obj){ obj.latitude.present? and obj.present }

  def address
    # [state, "AU"].compact.join(',')
    [state, country].compact.join(", ")

    # return "19 Peachey Rd, Davoren Park SA 5113, Australia"
    # [address_1, address_2, city, state, country].compact.join(',')
    # [state, country].compact.join(', ')
  end

  def default_image
    images.first
  end

  # def average_rating
  #   reviews.average(:rating)
  # end
  def available_dates
    next_reservation = reservations.future_reservations.first
    # next_reservation = reservations.where("reservation_date >  ?", Date.today).order(:reservation_date).first
    date_format = "%b %e"
    return Date.tomorrow.strftime(date_format)..Date.today.end_of_year.strftime(date_format) if next_reservation.nil?

    Date.tomorrow.strftime(date_format)..next_reservation.reservation_date.strftime(date_format)
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :property
  belongs_to :user

  validates :reservation_date, presence: true

  scope :future_reservations, -> { where("reservation_date > ?", Date.today).order(:reservation_date) }
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :rating, presence: true, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5, only_integer: true}
  belongs_to :reviewable, polymorphic: true, counter_cache: true

  after_commit :update_average_rating, on: [:create, :update]
  def update_average_rating
    reviewable.update!(average_rating: reviewable.reviews.average(:rating))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_properties, through: :favorites, source: :property
  has_many :reservations, dependent: :destroy
  has_many :reserved_properties, through: :reservations, source: :property

  after_create :create_profile

  def create_profile
    self.profile = Profile.new
    save!
  end
end

app/controllers/api/favorites_controller.rb
module Api
  class FavoritesController < ApplicationController
    protect_from_forgery with: :null_session
    # before_action :authenticate_user!

    def create
      favorite = Favorite.create!(favorite_params)

      respond_to do |format|
        format.json do
          render json: serialize_favorite(favorite), status: :created
        end
      end
    end

    def destroy
      favorite = Favorite.find(params[:id])
      favorite.destroy

      respond_to do |format|
        format.json do
          render json: serialize_favorite(favorite), status: 204
        end
      end
    end

    private

    def serialize_favorite(favorite)
      FavoriteSerializer.new(favorite).serializable_hash.to_json
    end

    def favorite_params
      params.permit(:user_id, :property_id)
    end
  end
end

app/controllers/api/users_by_emails_controller.rb
# frozen_string_literal: true

module Api
  class UsersByEmailsController < ApplicationController
    def show
      user = User.find_by!(email: params[:email])

      respond_to do |format|
        format.json do
          render json: user.to_json, status: :ok
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      respond_to do |format|
        format.json do
          render json: {error: e.message}.to_json, status: 404
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
  end
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  def show
    @property = Property.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_user_auth_form.html.erb
<div data-controller="users-by-email-auth">
  <div>
    <div class="flex">
      <div class="flex-none cursor-pointer" data-modal-target="closeButton">
        <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
      <div class="flex-grow">
        <h3 class="text-md leading-6 font-medium text-center text-gray-900 mb-4" id="modal-title">Log in or Sign up</h3>
      </div>
    </div>

    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="relative">
      <div class="absolute inset-0 flex items-center" aria-hidden="true">
        <div class="w-full border-t border-gray-300"></div>
      </div>
      <div class="relative flex justify-center">
      </div>
    </div>
    <div class="pt-4">
      <h4 class="text-lg text-gray-900 leading-6 mt-2 font-medium">Welcome to Globalbnb</h4>
      <div data-users-by-email-auth-target="emailWrapper" class="relative border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-black focus-within:border-black mt-6 red-500">
        <label for="email" class="block text-xs font-medium text-gray-900 ">Email</label>
        <input data-users-by-email-auth-target="email" type="email" name="email" id="email" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:outline-none sm:text-sm" placeholder="you@example.com">
        <div data-users-by-email-auth-target="invalidSvg" class="hidden absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
          <!-- Heroicon name: solid/exclamation-circle -->
          <svg class="h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        </div>
      </div>
      <p data-users-by-email-auth-target="errorMessage" class="hidden mt-2 text-sm text-red-600" id="email-error">Your password must be less than 4 characters.</p>
    </div>
  </div>
  <div class="my-5 sm:my-6">
    <button data-users-by-email-auth-target="submit" type="button" class="inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-primary text-base font-medium text-white hover:bg-primary focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary sm:text-sm">Continue</button>
  </div>
</div>



<div class="relative">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
  <div class="relative flex justify-center">
    <span class="px-2 bg-white text-sm text-gray-500"> or </span>
  </div>
</div>

<div class="mt-5 sm:mt-6">
  <button type="button" class="w-full inline-flex justify-center items-center px-4 py-2 border border-black shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-black">
    <svg class="-ml-1 mr-3 h-5 w-5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" style="height: 20px; width: 20px; display: block; fill: currentcolor;"><defs><path id="a" d="M.001 0H24v23.854H.001z"></path></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"></use></mask><path d="M24 12c0-6.627-5.373-12-12-12S0 5.373 0 12c0 5.99 4.388 10.954 10.125 11.854V15.47H7.078V12h3.047V9.356c0-3.007 1.792-4.668 4.533-4.668 1.312 0 2.686.234 2.686.234v2.953H15.83c-1.491 0-1.956.925-1.956 1.874V12h3.328l-.532 3.469h-2.796v8.385C19.612 22.954 24 17.99 24 12" fill="#1877F2" mask="url(#b)"></path><path d="M16.671 15.469L17.203 12h-3.328V9.749c0-.949.465-1.874 1.956-1.874h1.513V4.922s-1.374-.234-2.686-.234c-2.741 0-4.533 1.66-4.533 4.668V12H7.078v3.469h3.047v8.385a12.09 12.09 0 003.75 0V15.47h2.796" fill="#FFF"></path></g></svg>
    Continue with Facebook
  </button>
</div>

app/views/home/index.html.erb
<div data-controller="geolocation"
     class="container mx-auto py-24"
     data-latitude="<%= current_user&.profile&.latitude %>"
     data-longitude="<%= current_user&.profile&.longitude %>"
>
  <ul role="list" class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-4 sm:gap-x-6 lg:grid-cols-5 xl:gap-x-8">
    <% @properties.each do |property| %>
      <%= link_to property_path(property) do %>
        <li
          class="relative"
          data-geolocation-target="property"
          data-latitude="<%= property.latitude %>"
          data-longitude="<%= property.longitude %>"
        >
          <div class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 overflow-hidden relative">

            <%= image_tag property.default_image, class: "object-cover pointer-events-none group-hover:opacity-75" %>
            <button type="button" class="absolute inset-0 focus:outline-none">
            </button>
            <div class="flex flex-row-reverse p-2 absolute top-0 right-0">
              <svg
                class="w-8 h-8 cursor-pointer"
                data-controller="favorites"
                data-user-logged-in="<%= user_signed_in? %>"
                data-user-id="<%= current_user&.id %>"
                data-property-id="<%= property.id %>"
                data-favorite-id="<%= current_user.favorites.find_by(property: property).id if current_user&.favorited_properties&.include?(property) %>"
                data-favorited="<%= current_user&.favorites&.where(property: property)&.exists? %>"
                data-action="click->favorites#favorite"
                fill="<%= current_user&.favorited_properties&.include?(property) ? 'red' : 'white' %>"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
                stroke-width="2"
              >
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
              </svg>
            </div>
          </div>
          <p class="mt-2 block text-sm font-medium text-gray-900 truncate pointer-events-none"><%= property.city %>, <%= property.state %> <%= property.country %></p>
          <div class="flex items-center">
            <p class="block text-sm font-medium text-gray-500 pointer-events-none text-black"><%= property.average_rating.to_f.round(2)%></p>
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"></path>
            </svg>
          </div>
          <p data-distance-away class="block text-sm font-medium text-gray-500 pointer-events-none"></p>
          <p class="block text-sm font-medium text-gray-500 pointer-events-none"><%= property.available_dates.first %> - <%= property.available_dates.last %></p>
          <p class="block text-sm font-medium text-gray-500 pointer-events-none"><span class="text-black"><%= humanized_money_with_symbol(property.price) %> per night</span></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vacation Home & Condo Rentals-Airb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/properties/_share_property.html.erb
<div
  data-controller="share-modal"
  data-share-url="<%= url_for(only_path: false) %>"
>
<div class="flex mb-5">
    <div class="flex-none cursor-pointer" data-modal-target="closeButton">
      <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </div>
</div>
<div class="flex">
  <p class="text-2xl font-medium">Share this place with friends and family</p>
</div>
<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
  <div class="relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
    <div class="flex-shrink-0">
      <img class="h-16 w-16 rounded-lg" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
    </div>
    <div class="min-w-0 flex-1">
      <p class="text-sm font-medium text-gray-900"><%= @property.name %></p>
    </div>
  </div>

  <!-- More people... -->

    <!-- More people... -->
    <div data-action="click->share-modal#copyLink" class="cursor-pointer hover:bg-gray-100 relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
      <div class="flex-shrink-0">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" stroke-width="1" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M272 0H396.1c12.7 0 24.9 5.1 33.9 14.1l67.9 67.9c9 9 14.1 21.2 14.1 33.9V336c0 26.5-21.5 48-48 48H272c-26.5 0-48-21.5-48-48V48c0-26.5 21.5-48 48-48zM48 128H192v64H64V448H256V416h64v48c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V176c0-26.5 21.5-48 48-48z"/></svg>    <div class="min-w-0 flex-1">
        <p class="text-sm font-medium text-gray-900">Copy</p>
      </div>
      </div>

      <div data-action="click->share-modal#shareFacebook" class="cursor-pointer hover:bg-gray-100 relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
        <div class="flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" stroke-width="1" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"/></svg>    <div class="min-w-0 flex-1">
          <p class="text-sm font-medium text-gray-900">Facebook</p>
        </div>
        </div>

        <div data-action="click->share-modal#shareWhatsapp" class="cursor-pointer hover:bg-gray-100 relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
          <div class="flex-shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" stroke-width="1" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 59.7 94.8 83.8 35.2 15.2 49 16.5 66.6 13.9 10.7-1.6 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z"/></svg>
          </div>
          <div class="min-w-0 flex-1">
            <p class="text-sm font-medium text-gray-900">WhatsApp</p>
          </div>
        </div>

        <div data-action="click->share-modal#shareTwitter" class="cursor-pointer hover:bg-gray-100 relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
          <div class="flex-shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" stroke-width="1" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>          </div>
          <div class="min-w-0 flex-1">
            <p class="text-sm font-medium text-gray-900">Twitter</p>
          </div>
        </div>
      </div>
    </div>

        <!-- More people... -->

</div>
</div>

app/views/shared/_modal.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div data-controller="modal"
     data-modal-trigger-id="<%= modal_trigger_id %>"
     id="modal-<%= modal_trigger_id %>-wrapper"
     class="hidden relative z-10"
     aria-labelledby="modal-title"
     role="dialog"
     aria-modal="true"
>
  <div class="hidden" id="modal_trigger_id" data-action="click#showModal"></div>
  <!--
    Background backdrop, show/hide based on modal state.

    Entering: "ease-out duration-300"
      From: "opacity-0"
      To: "opacity-100"
    Leaving: "ease-in duration-200"
      From: "opacity-100"
      To: "opacity-0"
  -->
  <div id="modal-<%= modal_trigger_id %>-backdrop"
       class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
       data-transition-enter="ease-out duration-300"
       data-transition-enter-start="opacity-0"
       data-transition-enter-end="opacity-100"
       data-transition-leave="ease-in duration-200"
       data-transition-leave-start="opacity-100"
       data-transition-leave-end="opacity-0"

  ></div>

  <div class="fixed z-10 inset-0 overflow-y-auto">
    <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
      <!--
        Modal panel, show/hide based on modal state.

        Entering: "ease-out duration-300"
          From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          To: "opacity-100 translate-y-0 sm:scale-100"
        Leaving: "ease-in duration-200"
          From: "opacity-100 translate-y-0 sm:scale-100"
          To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      -->
      <div id="modal-<%= modal_trigger_id %>-panel"
           class="hidden relative bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-xl sm:w-full sm:p-6"
           data-transition-enter="transition ease-out duration-300"
           data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
           data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
           data-transition-leave="ease-in duration-200"
           data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
           data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
     >
        <%= render modal_content %>
      </div>
    </div>
  </div>
</div>